name: getx_playground
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  get: 4.3.8
  faker: 2.0.0
  supercharged: 2.1.1
  json_serializable: ^5.0.2
  json_annotation: ^4.1.0
  flutter_zoom_drawer: 2.1.1
  built_value: 8.1.2
  built_collection: 5.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  lints: 1.0.1
  build_runner: ^2.1.2
  built_value_generator: ^8.1.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

